name: fl_wework_movies
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cached_network_image: 3.2.3
  connectivity_plus: 5.0.1
  cupertino_icons: 1.0.2
  dartz: 0.10.1
  dio: 5.3.3
  floor: 1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_spinkit: 5.2.1
  flutter_svg: 1.1.6
  geocode: 1.0.3
  geocoding: 3.0.0
  geolocator: 11.0.0
  get_it: 7.6.0
  http:
  jiffy: 6.0.0
  material_design_icons_flutter: 7.0.7296
  path_provider: 2.0.11
  uuid: 3.0.7

dev_dependencies:
  build_runner: 2.3.3
  floor_generator: 1.4.2
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf